/******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Pre-Compile Configuration post build file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: Remon Gerges
 ******************************************************************************/


#include "Port.h"


/* PB structure used with Port_Init API */
const Port_ConfigType Port_PinConfig = {
		PORT_PortA , PORT_Pin0, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortA , PORT_Pin1, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortA , PORT_Pin2, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortA , PORT_Pin3, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortA , PORT_Pin4, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortA , PORT_Pin5, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortA , PORT_Pin6, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortA , PORT_Pin7, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,

		PORT_PortB , PORT_Pin0, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortB , PORT_Pin1, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortB , PORT_Pin2, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortB , PORT_Pin3, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortB , PORT_Pin4, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortB , PORT_Pin5, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortB , PORT_Pin6, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortB , PORT_Pin7, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,

		PORT_PortC , PORT_Pin0, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortC , PORT_Pin1, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortC , PORT_Pin2, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortC , PORT_Pin3, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortC , PORT_Pin4, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortC , PORT_Pin5, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortC , PORT_Pin6, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortC , PORT_Pin7, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,

		PORT_PortD , PORT_Pin0, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortD , PORT_Pin1, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortD , PORT_Pin2, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortD , PORT_Pin3, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortD , PORT_Pin4, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortD , PORT_Pin5, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortD , PORT_Pin6, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortD , PORT_Pin7, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,

		PORT_PortE , PORT_Pin0, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortE , PORT_Pin1, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortE , PORT_Pin2, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortE , PORT_Pin3, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortE , PORT_Pin4, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortE , PORT_Pin5, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,

		PORT_PortF , PORT_Pin0, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW , PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortF , PORT_Pin1, PORT_PIN_OUT, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortF , PORT_Pin2, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortF , PORT_Pin3, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , STD_ON, STD_ON,
		PORT_PortF , PORT_Pin4, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW,  PORT_PIN_MODE_DIO , STD_ON, STD_ON

};

